# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param xicom.use_bs_reader 1
set_msg_config -id {Common 17-41} -limit 10000000
create_project -in_memory -part xc7a35tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/verilog/exp6_exam_ultro/exp6_exam_ultro.cache/wt [current_project]
set_property parent.project_path E:/verilog/exp6_exam_ultro/exp6_exam_ultro.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/verilog/exp6_exam_ultro/exp6_exam_ultro.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/arranger.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/baud_gnr.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/controller.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/db_fsm.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/dec_cnt.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/detect.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/receiver.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/sender.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/sseg.v
  E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/new/top.v
}
read_ip -quiet E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
set_property used_in_implementation false [get_files -all e:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/constrs_1/new/top.xdc
set_property used_in_implementation false [get_files E:/verilog/exp6_exam_ultro/exp6_exam_ultro.srcs/constrs_1/new/top.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top top -part xc7a35tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef top.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb"
