
set_property PACKAGE_PIN D5 [get_ports {sseg_cnt[7]}]
set_property PACKAGE_PIN B4 [get_ports {sseg_cnt[6]}]
set_property PACKAGE_PIN A4 [get_ports {sseg_cnt[5]}]
set_property PACKAGE_PIN A3 [get_ports {sseg_cnt[4]}]
set_property PACKAGE_PIN B1 [get_ports {sseg_cnt[3]}]
set_property PACKAGE_PIN A1 [get_ports {sseg_cnt[2]}]
set_property PACKAGE_PIN B3 [get_ports {sseg_cnt[1]}]
set_property PACKAGE_PIN B2 [get_ports {sseg_cnt[0]}]
set_property PACKAGE_PIN R15 [get_ports rst_n]
set_property PACKAGE_PIN P17 [get_ports sysclk]
set_property PACKAGE_PIN L3 [get_ports uart_in]


set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports sysclk]
set_property IOSTANDARD LVCMOS33 [get_ports uart_in]
set_property IOSTANDARD LVCMOS33 [get_ports uart_out]
set_property PACKAGE_PIN N2 [get_ports uart_out]

set_property IOSTANDARD LVCMOS33 [get_ports {an_cnt[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_cnt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_cnt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {an_cnt[0]}]

set_property IOSTANDARD LVCMOS33 [get_ports {current_state[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_state[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_state[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_state[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {current_state[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_cnt[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_cnt[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_cnt[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_cnt[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_cnt[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_cnt[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_cnt[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {sseg_cnt[0]}]

set_property PACKAGE_PIN G2 [get_ports {an_cnt[3]}]
set_property PACKAGE_PIN C2 [get_ports {an_cnt[2]}]
set_property PACKAGE_PIN C1 [get_ports {an_cnt[1]}]
set_property PACKAGE_PIN H1 [get_ports {an_cnt[0]}]
set_property PACKAGE_PIN J4 [get_ports {current_state[4]}]
set_property PACKAGE_PIN H4 [get_ports {current_state[3]}]
set_property PACKAGE_PIN J3 [get_ports {current_state[2]}]
set_property PACKAGE_PIN J2 [get_ports {current_state[1]}]
set_property PACKAGE_PIN K2 [get_ports {current_state[0]}]

set_property -dict {PACKAGE_PIN P5 IOSTANDARD LVCMOS33} [get_ports {sw[0]}]
set_property -dict {PACKAGE_PIN P4 IOSTANDARD LVCMOS33} [get_ports {sw[1]}]
set_property -dict {PACKAGE_PIN P3 IOSTANDARD LVCMOS33} [get_ports {sw[2]}]
set_property -dict {PACKAGE_PIN P2 IOSTANDARD LVCMOS33} [get_ports {sw[3]}]
set_property -dict {PACKAGE_PIN R2 IOSTANDARD LVCMOS33} [get_ports {sw[4]}]


set_property -dict {PACKAGE_PIN D18 IOSTANDARD LVCMOS33} [get_ports bt_ctrl[4]        ]
set_property -dict {PACKAGE_PIN C16 IOSTANDARD LVCMOS33} [get_ports bt_ctrl[0]  ]
set_property -dict {PACKAGE_PIN H15 IOSTANDARD LVCMOS33} [get_ports bt_ctrl[1]         ]
set_property -dict {PACKAGE_PIN M2  IOSTANDARD LVCMOS33} [get_ports bt_ctrl[2]         ]
set_property -dict {PACKAGE_PIN E18 IOSTANDARD LVCMOS33} [get_ports bt_ctrl[3]            ]